Add bindings for Cairo.ImageSurface
gircore/gir.core pull request #578
Opened 2022-03-13 03:19 UTC by cameronwhite

- Add unit tests so that manually generated bindings have test coverage
- Ensure that `cairo_surface_destroy()` is called to decrement the reference count, and that `cairo_surface_reference()` is called when constructing from an unowned handle to increment the reference count

The changes related to cairo_surface_destroy() and  cairo_surface_reference() are something that I'd appreciate feedback on! The current solution feels like more of a workaround than a proper fix

The main issue is that the gir file doesn't capture Cairo's ref-counted memory management, so the auto-generated constructor and handles aren't correct. In this commit I adjusted the generated handles slightly so that the base `SurfaceHandle` implements `ReleaseHandle()`, allowing it to be overridden for `SurfaceOwnedHandle` in manually written code that can provide the correct cleanup function. The other change is to add a special constructor for `SurfaceUnownedHandle's` that bumps the reference count and moves it into an owned handle to decrement the refcount when finalized, so that the native surface stays alive for the duration of the managed object

Another idea could be to somehow skip generating this code entirely so that manual bindings don't have to work around incorrect bits of generated code. All of these cairo records have `foreign="1"` in the gir file and are otherwise empty, so maybe that should be used to skip generating code for opaque types that will probably be incorrect?

2022-03-13 07:31 UTC, badcel requested changes

2022-03-13 20:11 UTC, cameronwhite commented on src/Tests/Libs/Cairo-1.0.Tests/ImageSurfaceTest.cs
> +    [TestClass, TestCategory("UnitTest")]
Yeah, that is odd that it succeeded on macOS... The log shows other libraries missing, so cairo must be installed by something that's available by default in the runner

2022-03-16 22:14 UTC, cameronwhite commented
Rebased on the latest develop branch!
Related to #584 I've left out the UnownedHandle change for now until we determine the proper approach for UnownedHandle's in general

2022-03-17 16:29 UTC, badcel approved these changes

2022-03-17 16:29 UTC, merged