Support global functions
gircore/gir.core pull request #724
Opened 2022-12-27 01:11 UTC by cameronwhite

This adds bindings for global functions (e.g. `g_set_application_name()`), as static functions like `GLib.Functions.SetApplicationName()`

This is still in progress - there are several errors to sort through from the parameter types used by the functions

2023-01-03 06:14 UTC, badcel requested changes
Thank you for the works! All in all it looks good. Only some minor updates needed.

2023-01-03 06:14 UTC, badcel commented on src/Generation/Generator/Renderer/Public/GlobalFunctions.cs
> +        call.Append($"{Namespace.GetPublicName(function.Namespace)}.Internal.Functions.{Function.GetName(function)}(");
Use `Namespace.GetInternalName()`

2023-01-03 23:34 UTC, cameronwhite commented on src/Generation/Generator/Renderer/Public/GlobalFunctions.cs
> +        .Where(f => f.Introspectable)
Good catch, I think I may have added that while looking into some of the errors fixed by other PRs.

2023-01-04 05:28 UTC, badcel approved these changes

2023-01-04 12:50 UTC, merged