Add a C test library for easier testing of the generated bindings
gircore/gir.core pull request #764
Opened 2023-01-16 05:55 UTC by cameronwhite

This is related to #504 - I decided to experiment with this after writing a C library to test out #763, and found it really useful to have a simple C function (which I could also add printouts to, etc) to test against
I think this could make it easier to have more extensive tests for correctness, which can run without a display and without requiring a lot of boilerplate code to call a function with the parameter type we want to test (e.g. having to construct a GTK application and widgets)

Still a work in progress, but wanted to get some initial feedback on whether this would be worth adding?
Also a couple questions:
- Currently I have this as a separate script. I wasn't sure about making this part of the default build since it adds the requirement of having a C toolchain, gir-related tools, etc?
- The library is currently generated into the `Libs` folder like everything else, but it could perhaps go elsewhere. I'm not sure if there are any things to watch out for with this, e.g. would it be pulled into the Nuget packages?

TODOs
- [ ] Needs testing on other platforms, currently only tested on macOS
- [ ] Add to CI build script

2023-01-16 07:27 UTC, badcel commented
I did not look at the code but the idea is very welcome!

See #504

2023-01-18 03:26 UTC, cameronwhite commented
I've got the Windows build sorted out now, so this is building and running the test successfully on all platforms 🎉

2023-01-18 05:50 UTC, badcel commented
Can you update the reademe's Build section and include an `dotnet build Gir.Core.Libraries.slnf`?

Additionally I think it would be helpful to explain why the solution filter exists.

2023-01-21 07:19 UTC, badcel requested changes
Thanks for your work, very well done. This helps a lot to establish a much improved testability of the generator it is very much appreciated.

Please fix the remaining remarks and it is good to go.

2023-01-21 07:25 UTC, badcel commented on src/Native/GirTestLib/primitivevaluetype.c
> +#include "primitivevaluetype.h"
Should the folder: `src/Native/GirTestLib/` be part of the solution to allow easy editing?

2023-01-21 19:55 UTC, cameronwhite commented
Thanks! I've pushed fixes for those issues

2023-01-21 23:08 UTC, merged