Sync'ed dependencies in csproj/gir/Module.cs
gircore/gir.core pull request #875
Opened 2023-05-31 07:56 UTC by fogzot

There are still some discrepancies between gir and csproj files, documented below. This changeset also normalize the format of csproj files moving metadata to the top and dependencies to the bottom.

Adw-1
- gir does not include GObject

cairo-1.0
- gir does not include GObject
- gir does not include GLib

freetype2-2.0
- gir does not include GObject
- gir does not include GLib
- Module.cs is missing

Gdk-4.0
- gir does not include GObject

GdkPixbuf-2.0
- gir does not include GObject
- gir includes GModule (that cannot be included by csproj)

Gst-1.0
- gir includes GModule (that cannot be included by csproj)

GstAudio-1.0
- gir includes GModule (that cannot be included by csproj)

GstBase-1.0
- gir includes GModule (that cannot be included by csproj)

GstPbutils-1.0
- gir does not include GObject

GstVideo-1.0
- gir does not include GObject

 I agree that my contribution may be licensed either under MIT or any version of LGPL license.

2023-06-01 19:14 UTC, badcel requested changes
Thank you! Very good work. There was some overhaul pretty necessary. Especially in `Gtk.Module` there was a lot of stuff which did not belong there.

In general I opted to remove explicit references to GObject if possible (in those cases it is referenced implicitly).  Otherwise every module would need to reference GObject explicitly. I think this keeps the dependencies more in line with the gir files. Please see my comments.

Regarding freetype please remove it's `GLib` dependency. As it does not define a "shared-library" in the `namespace` tag, please don't add a `Module.cs`. There would be the code to sett the DLL-Library name, which is not possible due to the missing "shared-library" attribute.

2023-06-01 19:14 UTC, badcel commented on src/Libs/Adw-1/Adw-1.csproj
> +    <ProjectReference Include="..\GObject-2.0\GObject-2.0.csproj" />
Please do not add an explicit reference for GObject.

2023-06-01 19:14 UTC, badcel commented on src/Libs/Gdk-4.0/Gdk-4.0.csproj
>      <ProjectReference Include="..\GObject-2.0\GObject-2.0.csproj" />
Please remove explicit GObject initialization

2023-06-01 19:14 UTC, badcel commented on src/Libs/Gdk-4.0/Public/Module.cs
>          GObject.Module.Initialize();
Please remove explicit GObject initialization

2023-06-01 19:14 UTC, badcel commented on src/Libs/GdkPixbuf-2.0/GdkPixbuf-2.0.csproj
> +    <ProjectReference Include="..\GObject-2.0\GObject-2.0.csproj" />
Please remove explicit GObject reference

2023-06-01 19:14 UTC, badcel commented on src/Libs/GdkPixbuf-2.0/Public/Module.cs
>          GObject.Module.Initialize();
Please remove explicit GObject reference

2023-06-14 19:05 UTC, fogzot commented
I applied all changes, as requested.

2023-06-23 16:01 UTC, badcel approved these changes
Looks good to me 👍. Thanks for your contribution.

2023-06-23 16:02 UTC, merged